Add barcodes.tsv file required to run test dataset with scsplit
nf-core/test-datasets pull request #1173
Opened 2024-04-05 10:14 UTC by IreneRobles

Hi, 

I am developing the scsplit module. I modify my tests to use the same dataset as `popscle`, but I need an extra `barcodes.tsv` file. I tried some `barcode.tsv.gz` test datasets present in the branch, but they do not run, so I decided to add one that does.

Have a nice day,

Irene

2024-04-12 07:57 UTC, wxicu requested changes
Hi @IreneRobles  Thanks for adding the file. However the barcode file is also provided by popscle, not provided by hadge.

2024-04-12 07:57 UTC, wxicu commented on data/genomics/homo_sapiens/demultiplexing/README.md
Cell barcodes are also provided by popscle (Source: https://drive.google.com/file/d/1n52EZFz83W6lNN8jo8r1hQqVoTipLhoT/view?usp=drive_link)

2024-04-12 08:19 UTC, IreneRobles commented on data/genomics/homo_sapiens/demultiplexing/README.md
Now the cell barcodes are from popscle, :)

2024-04-12 08:21 UTC, IreneRobles commented
Hi @wxicu ,

I switched the barcodes. Now they are from popscle. :)

2024-04-12 11:45 UTC, jfy133 reviewed
You also need to update the main README of the whole repo (well on that branch), describing how the file was generated not just the demultiplex specific README.

Also the file is very large at 12MB, is there anyway it could be made smaller?

2024-04-16 15:37 UTC, IreneRobles commented
Hi @jfy133 and @wxicu ,
- I have reduced the  size of `barcodes.tsv` file so it only contains the barcodes of the cells in `chr21.bam`
- I have also updated the `README.md`s
Thank you for taking a look at my branch!

2024-04-18 09:32 UTC, jfy133 approved these changes

2024-04-18 09:33 UTC, jfy133 commented
One last thing now I thin of it: It looks like the barcodes might be specific to a particular library build.technology? If yes maybe `barcodes.csv` could be renamed to reflect that.

If they are generic barcodes it's probably fine :)

2024-04-18 18:25 UTC, wxicu approved these changes

2024-04-22 10:23 UTC, merged