Test sample sheet for teh pairgenomealign pipeline
nf-core/test-datasets pull request #1188
Opened 2024-04-24 06:11 UTC by U13bs1125

Hello,

Sequel to my approval to develop an nf-core pipeline 'pairgenomealign', I will like to add this branch to enable quick pipelie test.

regards.

2024-05-15 07:48 UTC, maxulysse commented
@U13bs1125 I assume you'd like a `pairgenomealign` branch instead maybe?

2024-05-15 07:49 UTC, maxulysse requested changes
I would recommend having this file in a particular folder

2024-05-17 01:07 UTC, U13bs1125 commented
We put the Samplesheet into a tests folder.

Thanks

2024-05-28 08:16 UTC, maxulysse approved these changes

2024-05-28 08:17 UTC, merged