Adds taxprofiler databases
nf-core/test-datasets pull request #477
Opened 2022-03-21 19:40 UTC by jfy133

2022-03-21 19:45 UTC, jfy133 commented on README.md
> +
```suggestion
#### Kraken2

```bash
kraken2-build --download-taxonomy --db taxprofiler-testdb
gunzip ../raw/*.gz
kraken2-build --add-to-library ../raw/GCF_000146045.2_R64_genomic.fna --db taxprofiler-testdb/
kraken2-build --add-to-library ../raw/NC_012920.1.fa --db taxprofiler-testdb/
kraken2-build --build --db taxprofiler-testdb/
kraken2-build --clean --db taxprofiler-testdb/
```
```

2022-03-22 16:30 UTC, sofstam approved these changes
Looks good to me!

2022-03-22 20:49 UTC, Midnighter requested changes
Thank you for handling the test data 🙂 

I suggest two small improvements to the readme.

I was also wondering when adding test data for the Bracken module, is there really a point in storing the directories and files in addition to the compressed tar archives? Since you provide the commands to replicate, it seems redundant.

2022-03-22 20:49 UTC, Midnighter commented on README.md
> +FASTQ files are stored under `data/fasta/`
```suggestion
FASTA files are stored under `data/fasta/`
```

2022-03-22 20:49 UTC, Midnighter commented on README.md
> +kraken2-build --clean --db taxprofiler-testdb/
````suggestion
kraken2-build --clean --db taxprofiler-testdb/
```
````

2022-03-23 06:48 UTC, jfy133 commented
> I was also wondering when adding test data for the Bracken module, is there really a point in storing the directories and files in addition to the compressed tar archives? Since you provide the commands to replicate, it seems redundant.

Whoops, correct!

2022-03-23 09:02 UTC, Midnighter approved these changes

2022-03-23 09:03 UTC, merged