Adding Krona test database
nf-core/test-datasets pull request #521
Opened 2022-05-02 16:27 UTC by lescai

This PR adds a krona test database to the Metagenome folder of sars-cov-2.
The added files allows more realistic tests of the krona modules, following the addition of kraken reports to this repository.

2022-05-02 18:42 UTC, jfy133 requested changes
Please update README, but otherwise good to go I think, file suffix could be `tsv` or similar though rather than `tab` (unless it's direct output from Krona)

2022-05-02 19:41 UTC, lescai commented
exactly :) ktUpdateTaxonomy.sh creates a file called "taxonomy.tab" so I thought best to reflect that. The ktimporttaxonomy I  believe (haven't tried though) expects a .tab file inside the folder passed as database

2022-05-02 19:59 UTC, lescai reviewed
Should be ok now :) thanks for spotting the readme!

2022-05-03 06:17 UTC, jfy133 approved these changes

2022-05-03 06:18 UTC, merged