feat: add minimal kraken2/Bracken database
nf-core/test-datasets pull request #599
Opened 2022-09-06 13:30 UTC by Midnighter

I suggest to add a kraken2/Bracken database. This one comes from the modules test data and is based on the SARS-CoV-2 genome. So it's probably not well suited to taxprofiler but is hopefully enough for the tests.

2022-09-06 13:33 UTC, jfy133 requested changes
If possible please document it on the main README (so we know how to reconstruct it if we ever need to ;) )

2022-09-06 13:36 UTC, Midnighter commented
I really wish we would use pipelines to create these test data, too. Always so painful to set up.

2022-09-06 13:49 UTC, jfy133 commented
> I really wish we would use pipelines to create these test data, too. Always so painful to set up.

Maybe we should add a db creation workflow... would only be another 8 modules :grimacing:

2022-10-12 08:28 UTC, jfy133 approved these changes

2022-10-12 08:34 UTC, merged