Openms idxml
nf-core/test-datasets pull request #643
Opened 2022-10-11 09:56 UTC by rolivella

This is for uploading data to test OpenMS idXML module

2022-10-11 10:06 UTC, ggabernet commented
Hi @rolivella , thanks for adding the test data! Could you have a look at the `README.md` and add the data in the corresponding subfolder (e.g. `proteomics`)? Also a short description of where the data comes from

2022-10-11 12:02 UTC, rolivella commented
@ggabernet I just added the documentation and pull request

2022-10-11 12:04 UTC, JoseEspinosa requested changes
Can see any changes in the readme :thinking: 
Maybe also it will be nice to rename the file in a more descriptive way.

2022-10-11 13:49 UTC, rolivella commented
@JoseEspinosa I already made your requested changes. Could you merge please?

2022-10-11 13:56 UTC, ggabernet approved these changes
Looks good to me know, even though if you have a source where you took the data from, it would be great to also add the reference here

2022-10-20 07:48 UTC, ggabernet commented
Hi @rolivella, checking this PR again, we try to keep an orderly folder structure, so that it will be easy to find the test data by everyone.
It seems like this is the first proteomics dataset! 🎉 
I would be therefore great to add it to a new directory called: "proteomics", and a subdirectory with the name of the species that the data comes from. See the other directory structure for `e.g. genomics` for an inspiration.

2022-10-20 09:06 UTC, rolivella commented
Hi @ggabernet I think that there's already a folder called "proteomics" here: 

https://github.com/nf-core/test-datasets/tree/modules/data/proteomics

But is not following the structure you mentioned with the species and so on. What should I do?

2022-10-20 11:15 UTC, ggabernet commented
In that case you can add a subdirectory under `proteomics` with the species name, and add your test data underneath. So that other proteomics datasets can follow the recommended structure 😄

2022-10-20 13:51 UTC, rolivella commented
@ggabernet ok! I'll do it and let you know!

2022-10-24 11:15 UTC, ggabernet reviewed
Looks good, I would just also add the folder in the readme file as suggested

2022-10-24 11:15 UTC, ggabernet commented on README.md
> +  - 'BSA_QC_file.idXML': identifications file for Bovine (BSA) organism coming from an OMSSA search engine.
```suggestion

- Bos taurus
  - idxml: 
    - 'BSA_QC_file.idXML': identifications file for Bovine (BSA) organism coming from an OMSSA search engine.
```

2022-10-24 11:57 UTC, ggabernet commented
Great, looks good to me then! @JoseEspinosa is there any other changes that you wanted there?

2022-10-24 13:01 UTC, JoseEspinosa approved these changes
LGTM @ggabernet ! Very nice 🚀

2022-10-25 10:52 UTC, merged