Test data for cellranger-atac
nf-core/test-datasets pull request #847
Opened 2023-04-04 15:39 UTC by heylf

2023-04-14 15:05 UTC, heylf commented
Test data for cellranger-atac from the cellranger-atac mkfastq test data. It is downsamples but it needs human chr1, else it will not work properly.

2023-05-03 21:07 UTC, klkeys commented on data/genomics/homo_sapiens/genome/chr1/genome.fasta.gz
@heylf can you elaborate on why chr1 is needed here? the repo has both chr21 and chr22 already. will your tests not work with either of them?

2023-05-04 08:57 UTC, heylf commented on data/genomics/homo_sapiens/genome/chr1/genome.fasta.gz
No, the chromosomes are too small to get an enrichment with the scATAC data. You either run into issues with not enough paired-end reads or with not enough peaks. I spent some time back to find a valid solution, but it always brought me back to chr1 (a bigger chromsome).

2023-05-04 08:58 UTC, heylf commented on data/genomics/homo_sapiens/genome/chr1/genome.fasta.gz
Additionally, a potential multiome test dataset (scRNA + scATAC) you run into the same and stricter problem.

2023-05-04 17:57 UTC, klkeys commented on data/genomics/homo_sapiens/genome/chr1/genome.fasta.gz
understood. for my part, I'm game for adding whatever test data are necessary, but others might (justifiably!) note that the chr1 FASTA adds a lot of data (>70MB) to an already bloated repository

by chance do your scATAC-Seq reads have corresponding scRNA-Seq data? that would encourage reuse of your chr1 reference sequence and ATAC FASTQs for testing a cellranger-arc module

there is a previous effort to furnish those data (https://github.com/nf-core/test-datasets/pull/713/files) but it appears to have stalled

2023-05-05 08:35 UTC, heylf commented on data/genomics/homo_sapiens/genome/chr1/genome.fasta.gz
Yes, I know that is why I tried to avoid it :(

Not yet. I need to test the scATAC together with the scRNA-Seq. It might be that I will update the scATAC for the cellranger-arc modules, but the plan is that the reference is reuused for the multiome and that scATAC works together with the scRNA-Seq. 

I will check out the PR you have posted. That might a good point to circumvent this whole issue with chr1.

2023-05-10 18:18 UTC, klkeys commented on data/genomics/homo_sapiens/genome/chr1/genome.fasta.gz
@heylf a wild thought: would a combined chr21 and chr22 reference accomplish what you need?

you would need to pull the two pairs of FASTA + GTF from this repo, but you could potentially [append one file to another](https://www.nextflow.io/docs/latest/script.html#basic-read-write) when staging files for your `cellranger-atac` module tests

maybe something like this?
```
big_fasta = file("chr21.fa", checkIfExists:true)
chr22_ref = file("chr22.fa", checkIfExist:true)
big_fasta.append(chr22_ref.text)
// repeat with corresponding GTF files
```

2023-05-17 12:35 UTC, heylf commented on data/genomics/homo_sapiens/genome/chr1/genome.fasta.gz
@klkeys 

I tested now **(a) the multiome data** (from https://github.com/nf-core/test-datasets/pull/713/files) --> does not work :-1: (b) combining chr21 and chr22 --> does not work :-1: 

Sorry, I would leave it with this test data unless another person finds something better.

2023-05-17 15:29 UTC, klkeys commented on data/genomics/homo_sapiens/genome/chr1/genome.fasta.gz
that's a bummer ☹️ 

thank you for following up @heylf

chr1 it is then 👍🏼

2023-05-17 15:45 UTC, klkeys requested changes
noting that this _is_ a pretty big data dump, but @heylf showed that the intended module tests don't seem to work on the existing chr21 and chr22 test data

only missing pieces are small bookkeeping details
* shift the data to new 10x Genomics data path
 `data/genomics/homo_sapiens/10xgenomics/cellranger-atac`, see discussion [here](https://github.com/nf-core/test-datasets/pull/878#issuecomment-1543437387)
* update the README in two places:
  * `data/genomics/homo_sapiens/genome/chr1` new section for added chr1 data
  * `data/genomics/homo_sapiens/10xgenomics/cellranger-atac` new section for added scATAC-Seq data

one those are set, I'm happy to approve 👍🏼

2023-05-17 15:45 UTC, klkeys commented on data/genomics/homo_sapiens/illumina/10xgenomics/test_scATAC_S1_L001_I1_001.fastq.gz
move to `data/genomics/homo_sapiens/10xgenomics/cellranger-atac/test_scATAC_S1_L001_I1_001.fastq.gz`

2023-05-17 15:45 UTC, klkeys commented on data/genomics/homo_sapiens/illumina/10xgenomics/test_scATAC_S1_L001_R1_001.fastq.gz
move to `data/genomics/homo_sapiens/10xgenomics/cellranger-atac/test_scATAC_S1_L001_R1_001.fastq.gz`

2023-05-17 15:45 UTC, klkeys commented on data/genomics/homo_sapiens/illumina/10xgenomics/test_scATAC_S1_L001_R2_001.fastq.gz
move to `data/genomics/homo_sapiens/10xgenomics/cellranger-atac/test_scATAC_S1_L001_R2_001.fastq.gz`

2023-05-17 15:45 UTC, klkeys commented on data/genomics/homo_sapiens/illumina/10xgenomics/test_scATAC_S1_L001_R3_001.fastq.gz
move to `data/genomics/homo_sapiens/10xgenomics/cellranger-atac/test_scATAC_S1_L001_R3_001.fastq.gz`

2023-05-19 12:33 UTC, heylf commented
@klkeys done!

2023-05-19 17:41 UTC, merged